namespace SpriteKind {
    export const Floor = SpriteKind.create()
}
sprites.onDestroyed(SpriteKind.Food, function (sprite) {
    if (randint(0, 1) == 0) {
        mySprite2.setPosition(152, randint(0, 10))
        mySprite2.vx = -50
    }
    if (randint(0, 1) == 1) {
        mySprite3.setPosition(152, randint(0, scene.screenHeight()))
        mySprite3.vx = -50
    }
})
sprites.onOverlap(SpriteKind.Food, SpriteKind.Enemy, function (sprite, otherSprite) {
    mySprite2.setPosition(152, randint(0, scene.screenHeight()))
    mySprite2.vx = -50
    mySprite3.setPosition(152, randint(0, scene.screenHeight()))
    mySprite3.vx = -50
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    controller.moveSprite(mySprite, 0, 75)
    mySprite.vy += 0
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    sprites.destroy(mySprite2)
    mySprite2 = sprites.create(img`
        . . . f f f f f f f f f f . . . 
        . . f f 1 1 5 5 5 5 5 5 f f . . 
        . f f 1 1 5 5 5 5 5 5 5 5 f f . 
        f f 1 1 5 f f f f f f 5 5 5 f f 
        f 1 1 5 f f 1 1 5 5 f f 5 5 5 f 
        f 1 5 f f 1 1 5 5 5 5 f f 5 5 f 
        f 5 5 f 1 1 5 f f 5 5 5 f 5 5 f 
        f 5 5 f 1 5 f f f f 5 5 f 5 5 f 
        f 5 5 f 5 5 f f f f 5 5 f 5 5 f 
        f 5 5 f 5 5 5 f f 5 5 5 f 5 5 f 
        f 5 5 f f 5 5 5 5 5 5 f f 5 5 f 
        f 5 5 5 f f 5 5 5 5 f f 5 5 5 f 
        f f 5 5 5 f f f f f f 5 5 5 f f 
        . f f 5 5 5 5 5 5 5 5 5 5 f f . 
        . . f f 5 5 5 5 5 5 5 5 f f . . 
        . . . f f f f f f f f f f . . . 
        `, SpriteKind.Food)
    mySprite2.setPosition(152, randint(0, scene.screenHeight()))
    mySprite2.vx = -50
})
let mySprite3: Sprite = null
let mySprite2: Sprite = null
let mySprite: Sprite = null
let myMenu = miniMenu.createMenu(
miniMenu.createMenuItem("Tiburon come coins", img`
    ..............fffcc.............
    ..............fbbddc............
    ...............fbbddc...........
    ccc............fcbbccf..........
    cbbcc.........ffccccccffffff....
    .cbbdc.....fffcbbbbbbbbbbbbbff..
    .fbbddc..ffcccbbbbcbcbbbbbbbbbff
    ..fbbdfffcccccbbbcbcbbffbbbbbcbf
    ..fcbbbcccccccbbbcbcb1ff1111bbbf
    ..fccbcccccccccbbbbbb11111111bf.
    .fcbbfffccccccccbbbb11cc33cccf..
    .fbbf...cbdbcccccbbb111c131cf...
    fbbf.....ccdddddfbbbc111c33f....
    fff........ccddfbbdbf1111ff.....
    .............cfbbdbfccccc.......
    ..............fffff.............
    `),
miniMenu.createMenuItem("Zelda bir", img`
    ........................
    ....ffffff..............
    ..ffeeeef2f.............
    .ffeeeef222f............
    .feeeffeeeef...cc.......
    .ffffee2222ef.cdc.......
    .fe222ffffe2fcddc.......
    fffffffeeeffcddc........
    ffe44ebf44ecddc.........
    fee4d41fddecdc..........
    .feee4dddedccc..........
    ..ffee44e4dde...........
    ...f222244ee............
    ...f2222e2f.............
    ...f444455f.............
    ....ffffff..............
    .....fff................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `)
)
miniMenu.setDimensions(myMenu, 150, 120)
miniMenu.setTitle(myMenu, "Quie juego")
effects.clouds.startScreenEffect()
mySprite = sprites.create(img`
    ..............fffcc.............
    ..............fbbddc............
    ...............fbbddc...........
    ccc............fcbbccf..........
    cbbcc.........ffccccccffffff....
    .cbbdc.....fffcbbbbbbbbbbbbbff..
    .fbbddc..ffcccbbbbcbcbbbbbbbbbff
    ..fbbdfffcccccbbbcbcbbffbbbbbcbf
    ..fcbbbcccccccbbbcbcb1ff1111bbbf
    ..fccbcccccccccbbbbbb11111111bf.
    .fcbbfffccccccccbbbb11cc33cccf..
    .fbbf...cbdbcccccbbb111c131cf...
    fbbf.....ccdddddfbbbc111c33f....
    fff........ccddfbbdbf1111ff.....
    .............cfbbdbfccccc.......
    ..............fffff.............
    `, SpriteKind.Player)
miniMenu.onButtonPressed(myMenu, miniMenu.Button.A, function (selection, selectedIndex) {
    miniMenu.close(myMenu)
    mySprite.setStayInScreen(true)
    mySprite2 = sprites.create(img`
        . . . f f f f f f f f f f . . . 
        . . f f 1 1 5 5 5 5 5 5 f f . . 
        . f f 1 1 5 5 5 5 5 5 5 5 f f . 
        f f 1 1 5 f f f f f f 5 5 5 f f 
        f 1 1 5 f f 1 1 5 5 f f 5 5 5 f 
        f 1 5 f f 1 1 5 5 5 5 f f 5 5 f 
        f 5 5 f 1 1 5 f f 5 5 5 f 5 5 f 
        f 5 5 f 1 5 f f f f 5 5 f 5 5 f 
        f 5 5 f 5 5 f f f f 5 5 f 5 5 f 
        f 5 5 f 5 5 5 f f 5 5 5 f 5 5 f 
        f 5 5 f f 5 5 5 5 5 5 f f 5 5 f 
        f 5 5 5 f f 5 5 5 5 f f 5 5 5 f 
        f f 5 5 5 f f f f f f 5 5 5 f f 
        . f f 5 5 5 5 5 5 5 5 5 5 f f . 
        . . f f 5 5 5 5 5 5 5 5 f f . . 
        . . . f f f f f f f f f f . . . 
        `, SpriteKind.Food)
    mySprite3 = sprites.create(img`
        ........................
        ....ffffff..............
        ..ffeeeef2f.............
        .ffeeeef222f............
        .feeeffeeeef...cc.......
        .ffffee2222ef.cdc.......
        .fe222ffffe2fcddc.......
        fffffffeeeffcddc........
        ffe44ebf44ecddc.........
        fee4d41fddecdc..........
        .feee4dddedccc..........
        ..ffee44e4dde...........
        ...f222244ee............
        ...f2222e2f.............
        ...f444455f.............
        ....ffffff..............
        .....fff................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    info.setScore(scene.screenHeight())
})
forever(function () {
    mySprite.vy = 65
})
