@namespace
class SpriteKind:
    Floor = SpriteKind.create()

def on_up_pressed():
    controller.move_sprite(mySprite, 0, 75)
    mySprite.vy += 0
controller.up.on_event(ControllerButtonEvent.PRESSED, on_up_pressed)

mySprite: Sprite = None
effects.clouds.start_screen_effect()
mySprite = sprites.create(img("""
        ..............fffcc.............
        ..............fbbddc............
        ...............fbbddc...........
        ccc............fcbbccf..........
        cbbcc.........ffccccccffffff....
        .cbbdc.....fffcbbbbbbbbbbbbbff..
        .fbbddc..ffcccbbbbcbcbbbbbbbbbff
        ..fbbdfffcccccbbbcbcbbffbbbbbcbf
        ..fcbbbcccccccbbbcbcb1ff1111bbbf
        ..fccbcccccccccbbbbbb11111111bf.
        .fcbbfffccccccccbbbb11cc33cccf..
        .fbbf...cbdbcccccbbb111c131cf...
        fbbf.....ccdddddfbbbc111c33f....
        fff........ccddfbbdbf1111ff.....
        .............cfbbdbfccccc.......
        ..............fffff.............
        """),
    SpriteKind.player)
mySprite.set_stay_in_screen(True)
mySprite2 = sprites.create(img("""
        . . . f f f f f f f f f f . . .
        . . f f 1 1 5 5 5 5 5 5 f f . .
        . f f 1 1 5 5 5 5 5 5 5 5 f f .
        f f 1 1 5 f f f f f f 5 5 5 f f
        f 1 1 5 f f 1 1 5 5 f f 5 5 5 f
        f 1 5 f f 1 1 5 5 5 5 f f 5 5 f
        f 5 5 f 1 1 5 f f 5 5 5 f 5 5 f
        f 5 5 f 1 5 f f f f 5 5 f 5 5 f
        f 5 5 f 5 5 f f f f 5 5 f 5 5 f
        f 5 5 f 5 5 5 f f 5 5 5 f 5 5 f
        f 5 5 f f 5 5 5 5 5 5 f f 5 5 f
        f 5 5 5 f f 5 5 5 5 f f 5 5 5 f
        f f 5 5 5 f f f f f f 5 5 5 f f
        . f f 5 5 5 5 5 5 5 5 5 5 f f .
        . . f f 5 5 5 5 5 5 5 5 f f . .
        . . . f f f f f f f f f f . . .
        """),
    SpriteKind.food)
mySprite3 = sprites.create(img("""
        ........................
        ....ffffff..............
        ..ffeeeef2f.............
        .ffeeeef222f............
        .feeeffeeeef...cc.......
        .ffffee2222ef.cdc.......
        .fe222ffffe2fcddc.......
        fffffffeeeffcddc........
        ffe44ebf44ecddc.........
        fee4d41fddecdc..........
        .feee4dddedccc..........
        ..ffee44e4dde...........
        ...f222244ee............
        ...f2222e2f.............
        ...f444455f.............
        ....ffffff..............
        .....fff................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        """),
    SpriteKind.enemy)
mySprite4 = sprites.create(img("""
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        . . . . . . . f f . . . . . . .
        . . . . . . 2 2 2 2 . . . . . .
        . . . . . f 2 2 2 2 f . . . . .
        . . . . . f 2 2 2 2 f . . . . .
        . . . . . . 2 2 2 2 . . . . . .
        . . . . . . . f f . . . . . . .
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        . . . . . . . . . . . . . . . .
        """),
    SpriteKind.projectile)
scene.set_background_color(15)
info.set_score(info.score())

def on_forever():
    mySprite.vy = 65
forever(on_forever)

def on_update_interval():
    mySprite2.set_position(152, randint(0, scene.screen_height()))
    mySprite2.vx = -50
game.on_update_interval(3000, on_update_interval)
