name: MakeCode Build & Release

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install PXT
        run: npm install -g pxt

      - name: Initialize, Install and Build
        run: |
          pxt target arcade
          pxt install
          pxt build --allhw # Esto genera el .uf2 para todos los hardwares compatibles

      - name: Upload to Latest Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: "Última Compilación Automática"
          body: "Compilación generada automáticamente. Descarga el archivo .uf2 para tu consola."
          draft: false
          prerelease: true
          files: |
            built/**/*.uf2
            built/**/*.elf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
