name: MakeCode Build & Release

on:
  push:
    branches:
      - main
      - master
    tags:        # <--- Las etiquetas ahora están dentro de push
      - 'v*'
  workflow_dispatch: # <--- Esto activa el botón manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install PXT
        run: |
          npm install -g pxt
          npm install

      - name: Build Project
        run: pxt build --all

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            built/binary.uf2
            built/binary.elf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
